/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterRouteImport } from './routes/master'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignSpectatorRouteImport } from './routes/campaign.spectator'
import { Route as CampaignSettingsRouteImport } from './routes/campaign.settings'
import { Route as CampaignProfileRouteImport } from './routes/campaign.profile'
import { Route as CampaignInventoryRouteImport } from './routes/campaign.inventory'
import { Route as CampaignEquipmentRouteImport } from './routes/campaign.equipment'
import { Route as CampaignDmRouteImport } from './routes/campaign.dm'
import { Route as CampaignBoostersRouteImport } from './routes/campaign.boosters'
import { Route as CampaignAchievementsRouteImport } from './routes/campaign.achievements'

const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignSpectatorRoute = CampaignSpectatorRouteImport.update({
  id: '/spectator',
  path: '/spectator',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignSettingsRoute = CampaignSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignProfileRoute = CampaignProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignInventoryRoute = CampaignInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignEquipmentRoute = CampaignEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignDmRoute = CampaignDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignBoostersRoute = CampaignBoostersRouteImport.update({
  id: '/boosters',
  path: '/boosters',
  getParentRoute: () => CampaignRoute,
} as any)
const CampaignAchievementsRoute = CampaignAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => CampaignRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/master': typeof MasterRoute
  '/campaign/achievements': typeof CampaignAchievementsRoute
  '/campaign/boosters': typeof CampaignBoostersRoute
  '/campaign/dm': typeof CampaignDmRoute
  '/campaign/equipment': typeof CampaignEquipmentRoute
  '/campaign/inventory': typeof CampaignInventoryRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/settings': typeof CampaignSettingsRoute
  '/campaign/spectator': typeof CampaignSpectatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/master': typeof MasterRoute
  '/campaign/achievements': typeof CampaignAchievementsRoute
  '/campaign/boosters': typeof CampaignBoostersRoute
  '/campaign/dm': typeof CampaignDmRoute
  '/campaign/equipment': typeof CampaignEquipmentRoute
  '/campaign/inventory': typeof CampaignInventoryRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/settings': typeof CampaignSettingsRoute
  '/campaign/spectator': typeof CampaignSpectatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaign': typeof CampaignRouteWithChildren
  '/master': typeof MasterRoute
  '/campaign/achievements': typeof CampaignAchievementsRoute
  '/campaign/boosters': typeof CampaignBoostersRoute
  '/campaign/dm': typeof CampaignDmRoute
  '/campaign/equipment': typeof CampaignEquipmentRoute
  '/campaign/inventory': typeof CampaignInventoryRoute
  '/campaign/profile': typeof CampaignProfileRoute
  '/campaign/settings': typeof CampaignSettingsRoute
  '/campaign/spectator': typeof CampaignSpectatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaign'
    | '/master'
    | '/campaign/achievements'
    | '/campaign/boosters'
    | '/campaign/dm'
    | '/campaign/equipment'
    | '/campaign/inventory'
    | '/campaign/profile'
    | '/campaign/settings'
    | '/campaign/spectator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaign'
    | '/master'
    | '/campaign/achievements'
    | '/campaign/boosters'
    | '/campaign/dm'
    | '/campaign/equipment'
    | '/campaign/inventory'
    | '/campaign/profile'
    | '/campaign/settings'
    | '/campaign/spectator'
  id:
    | '__root__'
    | '/'
    | '/campaign'
    | '/master'
    | '/campaign/achievements'
    | '/campaign/boosters'
    | '/campaign/dm'
    | '/campaign/equipment'
    | '/campaign/inventory'
    | '/campaign/profile'
    | '/campaign/settings'
    | '/campaign/spectator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignRoute: typeof CampaignRouteWithChildren
  MasterRoute: typeof MasterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/spectator': {
      id: '/campaign/spectator'
      path: '/spectator'
      fullPath: '/campaign/spectator'
      preLoaderRoute: typeof CampaignSpectatorRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/settings': {
      id: '/campaign/settings'
      path: '/settings'
      fullPath: '/campaign/settings'
      preLoaderRoute: typeof CampaignSettingsRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/profile': {
      id: '/campaign/profile'
      path: '/profile'
      fullPath: '/campaign/profile'
      preLoaderRoute: typeof CampaignProfileRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/inventory': {
      id: '/campaign/inventory'
      path: '/inventory'
      fullPath: '/campaign/inventory'
      preLoaderRoute: typeof CampaignInventoryRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/equipment': {
      id: '/campaign/equipment'
      path: '/equipment'
      fullPath: '/campaign/equipment'
      preLoaderRoute: typeof CampaignEquipmentRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/dm': {
      id: '/campaign/dm'
      path: '/dm'
      fullPath: '/campaign/dm'
      preLoaderRoute: typeof CampaignDmRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/boosters': {
      id: '/campaign/boosters'
      path: '/boosters'
      fullPath: '/campaign/boosters'
      preLoaderRoute: typeof CampaignBoostersRouteImport
      parentRoute: typeof CampaignRoute
    }
    '/campaign/achievements': {
      id: '/campaign/achievements'
      path: '/achievements'
      fullPath: '/campaign/achievements'
      preLoaderRoute: typeof CampaignAchievementsRouteImport
      parentRoute: typeof CampaignRoute
    }
  }
}

interface CampaignRouteChildren {
  CampaignAchievementsRoute: typeof CampaignAchievementsRoute
  CampaignBoostersRoute: typeof CampaignBoostersRoute
  CampaignDmRoute: typeof CampaignDmRoute
  CampaignEquipmentRoute: typeof CampaignEquipmentRoute
  CampaignInventoryRoute: typeof CampaignInventoryRoute
  CampaignProfileRoute: typeof CampaignProfileRoute
  CampaignSettingsRoute: typeof CampaignSettingsRoute
  CampaignSpectatorRoute: typeof CampaignSpectatorRoute
}

const CampaignRouteChildren: CampaignRouteChildren = {
  CampaignAchievementsRoute: CampaignAchievementsRoute,
  CampaignBoostersRoute: CampaignBoostersRoute,
  CampaignDmRoute: CampaignDmRoute,
  CampaignEquipmentRoute: CampaignEquipmentRoute,
  CampaignInventoryRoute: CampaignInventoryRoute,
  CampaignProfileRoute: CampaignProfileRoute,
  CampaignSettingsRoute: CampaignSettingsRoute,
  CampaignSpectatorRoute: CampaignSpectatorRoute,
}

const CampaignRouteWithChildren = CampaignRoute._addFileChildren(
  CampaignRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignRoute: CampaignRouteWithChildren,
  MasterRoute: MasterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
